concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "my-runner2"
  url = "https://gitlab.local"
  id = 2
  token = "glrt-t1_8tPUhUsxMx9CPyyexvt1"
  token_obtained_at = 2025-01-23T08:42:20Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  tls-ca-file = "/etc/gitlab-runner/certs/gitlab.local.crt"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
    network_mode = "gitlab_gitlab-network"  # Use the same network as GitLab
    extra_hosts = ["gitlab.local:172.18.0.4"]  # Map gitlab.local to GitLab's IP